// User
export const SET_USER_INFO = 'SET_USER_INFO'
export const RELATED_TABLE_INFO = 'RELATED_TABLE_INFO'
// List Filter
//    conditions
export const SET_FILTER_CONDITIONS = 'SET_FILTER_CONDITIONS'
export const SET_FILTER_CONDITIONS_BY_INDEX = 'SET_FILTER_CONDITIONS_BY_INDEX'
//    orders
export const SET_FILTER_ORDERABLE_FIELDS = 'SET_FILTER_ORDERABLE_FIELDS'
export const SET_FILTER_ORDERS = 'SET_FILTER_ORDERS'
export const SET_FILTER_ORDERS_BY_INDEX = 'SET_FILTER_ORDERS_BY_INDEX'
//    visible
export const SET_FILTER_VISIBLE_FIELDS = 'SET_FILTER_VISIBLE_FIELDS'
export const SET_FILTER_VISIBLES = 'SET_FILTER_VISIBLES'
//    select items
export const SET_FILTER_SELECT_ITEMS = 'SET_FILTER_SELECT_ITEMS'
// export const ADD_CONDITION = 'ADD_CONDITION';
export const SET_FILTER_UNIT_ID = 'SET_FILTER_UNIT_ID'
export const SET_FILTER_UNITS = 'SET_FILTER_UNITS'
export const SET_FILTER_CONSTANT = 'SET_FILTER_CONSTANT'

// entityList
export const SET_LIST_CLIENT_DATA = 'SET_LIST_CLIENT_DATA'
export const SET_LIST_SCHEMA_ID = 'SET_LIST_SCHEMA_ID'
export const SET_LIST_SCHEMA_ITEMS = 'SET_LIST_SCHEMA_ITEMS'
export const SET_LIST_SIDEBAR_VISIBLE = 'SET_LIST_SIDEBAR_VISIBLE'
